### ISSUE TITLE
Error while downloading updates

### ISSUE THREAD

**Issue by shinjisixteen** [elytra/CotM-Launcher#1]
Uploading 0 bytes...
Upload failed: Bad API request, api_paste_code was empty
[warning] Failed to download https://jenkins.nallar.me/job/TickProfiler/job/1.10.2/lastSuccessfulBuild/artifact/build/libs/TickProfiler-1.10.2.jenkins.31.jar
java.io.IOException: Did not get expected response code, got 522 for https://jenkins.nallar.me/job/TickProfiler/job/1.10.2/lastSuccessfulBuild/artifact/build/libs/TickProfiler-1.10.2.jenkins.31.jar
	at com.skcraft.launcher.util.HttpRequest.expectResponseCode(HttpRequest.java:169)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:252)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.download(HttpDownloader.java:229)
	at com.skcraft.launcher.install.HttpDownloader$HttpDownloadJob.run(HttpDownloader.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by AnsuzThurisaz** [comment]
The tickprofiler jenkins was down. Mirrored file for now, launcher updated.

**Comment by AnsuzThurisaz** [comment]
Confirmed fixed.
